"""file unique id

Revision ID: 07a2674c3356
Revises: 5b990251a940
Create Date: 2024-06-21 09:20:23.068254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a2674c3356'
down_revision: Union[str, None] = '5b990251a940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_unique_id', sa.String(length=100), nullable=True))
    op.alter_column('images', 'url',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'url',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('images', 'file_unique_id')
    # ### end Alembic commands ###
