"""cascade 2

Revision ID: 28dbb8a43906
Revises: 2dcf3bf5f951
Create Date: 2024-06-25 19:27:21.653076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28dbb8a43906'
down_revision: Union[str, None] = '2dcf3bf5f951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_categories_product_id_fkey', 'product_categories', type_='foreignkey')
    op.create_foreign_key(None, 'product_categories', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.create_foreign_key('product_categories_product_id_fkey', 'product_categories', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
