"""category

Revision ID: 2bc3c93f7ba8
Revises: 477b73621ee8
Create Date: 2024-06-12 22:58:43.155983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc3c93f7ba8'
down_revision: Union[str, None] = '477b73621ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'active')
    op.drop_column('categories', 'position')
    # ### end Alembic commands ###
