"""postiiton to brand

Revision ID: 477b73621ee8
Revises: 7b64a2d2c0b4
Create Date: 2024-06-09 16:47:08.272080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477b73621ee8'
down_revision: Union[str, None] = '7b64a2d2c0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('brands', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'active')
    op.drop_column('brands', 'position')
    # ### end Alembic commands ###
