"""cascade 2

Revision ID: c2521c67d0e1
Revises: b1c2288f8610
Create Date: 2024-06-25 19:30:01.629846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2521c67d0e1'
down_revision: Union[str, None] = 'b1c2288f8610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_product_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_product_id_fkey', 'images', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
