"""name nullable

Revision ID: e80e5e3091a5
Revises: 6dcb2ec8c5b7
Create Date: 2024-06-05 11:09:54.903242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e80e5e3091a5'
down_revision: Union[str, None] = '6dcb2ec8c5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'lang',
               existing_type=postgresql.ENUM('EN', 'RU', 'UZ', name='languageenums'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lang',
               existing_type=postgresql.ENUM('EN', 'RU', 'UZ', name='languageenums'),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
